language: "python"
python: "2.7"
sudo: false

addons:
  apt:
    packages:
      - libgmp-dev

env:
  global:
    - secure: "encUyxw60qlEkklDlaZh9eHX0UbymccgGbvMDnv3wzM46qAN1CcO8RGQvVLcMtpqBB5vd9zTlipldTBVdPU/22RqtDdWF+v7Cjt0ZmK/9ptAP3kixdqgsmp9gPBpYEJC12J3ZFgfjMW4Krr056CvvUKIslV+PO3m1VG6/fTAWKU="
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

cache:
  directories:
    - ~/.cache/pip

script: "sh .build.sh"
